// Code generated by microgen 1.0.5. DO NOT EDIT.

package transporthttp

import (
	transport "github.com/SurajKadam7/msg-info-service/msginfo_srv/transport"
	httpkit "github.com/go-kit/kit/transport/http"
	"net/url"
)

func NewHTTPClient(u *url.URL, opts ...httpkit.ClientOption) transport.EndpointsSet {
	return transport.EndpointsSet{
		AddEndpoint: httpkit.NewClient(
			"POST", u,
			_Encode_Add_Request,
			_Decode_Add_Response,
			opts...,
		).Endpoint(),
		DeleteEndpoint: httpkit.NewClient(
			"DELETE", u,
			_Encode_Delete_Request,
			_Decode_Delete_Response,
			opts...,
		).Endpoint(),
		GetAllEndpoint: httpkit.NewClient(
			"POST", u,
			_Encode_GetAll_Request,
			_Decode_GetAll_Response,
			opts...,
		).Endpoint(),
		UpdateEndpoint: httpkit.NewClient(
			"PUT", u,
			_Encode_Update_Request,
			_Decode_Update_Response,
			opts...,
		).Endpoint(),
	}
}
