// Code generated by microgen 1.0.5. DO NOT EDIT.

// Please, do not change functions names!
package transporthttp

import (
	"bytes"
	"context"
	"encoding/json"
	transport "github.com/SurajKadam7/msg-info-service/msginfo_srv/transport"
	"io"
	"net/http"
	"path"
)

func CommonHTTPRequestEncoder(_ context.Context, r *http.Request, request interface{}) error {
	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(request); err != nil {
		return err
	}
	r.Body = io.NopCloser(&buf)
	return nil
}

func CommonHTTPResponseEncoder(_ context.Context, w http.ResponseWriter, response interface{}) error {
	w.Header().Set("Content-Type", "application/json; charset=utf-8")
	return json.NewEncoder(w).Encode(response)
}

func _Decode_Add_Request(_ context.Context, r *http.Request) (interface{}, error) {
	var req transport.AddRequest
	err := json.NewDecoder(r.Body).Decode(&req)
	return &req, err
}

func _Decode_Delete_Request(_ context.Context, r *http.Request) (interface{}, error) {
	var req transport.DeleteRequest
	err := json.NewDecoder(r.Body).Decode(&req)
	return &req, err
}

func _Decode_GetAll_Request(_ context.Context, r *http.Request) (interface{}, error) {
	var req transport.GetAllRequest
	err := json.NewDecoder(r.Body).Decode(&req)
	return &req, err
}

func _Decode_Update_Request(_ context.Context, r *http.Request) (interface{}, error) {
	var req transport.UpdateRequest
	err := json.NewDecoder(r.Body).Decode(&req)
	return &req, err
}

func _Decode_Add_Response(_ context.Context, r *http.Response) (interface{}, error) {
	var resp transport.AddResponse
	err := json.NewDecoder(r.Body).Decode(&resp)
	return &resp, err
}

func _Decode_Delete_Response(_ context.Context, r *http.Response) (interface{}, error) {
	var resp transport.DeleteResponse
	err := json.NewDecoder(r.Body).Decode(&resp)
	return &resp, err
}

func _Decode_GetAll_Response(_ context.Context, r *http.Response) (interface{}, error) {
	var resp transport.GetAllResponse
	err := json.NewDecoder(r.Body).Decode(&resp)
	return &resp, err
}

func _Decode_Update_Response(_ context.Context, r *http.Response) (interface{}, error) {
	var resp transport.UpdateResponse
	err := json.NewDecoder(r.Body).Decode(&resp)
	return &resp, err
}

func _Encode_Add_Request(ctx context.Context, r *http.Request, request interface{}) error {
	r.URL.Path = path.Join(r.URL.Path, "add")
	return CommonHTTPRequestEncoder(ctx, r, request)
}

func _Encode_Delete_Request(ctx context.Context, r *http.Request, request interface{}) error {
	r.URL.Path = path.Join(r.URL.Path, "delete")
	return CommonHTTPRequestEncoder(ctx, r, request)
}

func _Encode_GetAll_Request(ctx context.Context, r *http.Request, request interface{}) error {
	r.URL.Path = path.Join(r.URL.Path, "get-all")
	return CommonHTTPRequestEncoder(ctx, r, request)
}

func _Encode_Update_Request(ctx context.Context, r *http.Request, request interface{}) error {
	r.URL.Path = path.Join(r.URL.Path, "update")
	return CommonHTTPRequestEncoder(ctx, r, request)
}

func _Encode_Add_Response(ctx context.Context, w http.ResponseWriter, response interface{}) error {
	return CommonHTTPResponseEncoder(ctx, w, response)
}

func _Encode_Delete_Response(ctx context.Context, w http.ResponseWriter, response interface{}) error {
	return CommonHTTPResponseEncoder(ctx, w, response)
}

func _Encode_GetAll_Response(ctx context.Context, w http.ResponseWriter, response interface{}) error {
	return CommonHTTPResponseEncoder(ctx, w, response)
}

func _Encode_Update_Response(ctx context.Context, w http.ResponseWriter, response interface{}) error {
	return CommonHTTPResponseEncoder(ctx, w, response)
}
