// Code generated by microgen 1.0.5. DO NOT EDIT.

package transporthttp

import (
	transport "github.com/SurajKadam7/msg-info-service/msginfo_srv/transport"
	http "github.com/go-kit/kit/transport/http"
	mux "github.com/gorilla/mux"
	http1 "net/http"
)

func NewHTTPHandler(endpoints *transport.EndpointsSet, opts ...http.ServerOption) http1.Handler {
	mux := mux.NewRouter()
	mux.Methods("POST").Path("/msginfo/").Handler(
		http.NewServer(
			endpoints.AddEndpoint,
			_Decode_Add_Request,
			_Encode_Add_Response,
			opts...))
	mux.Methods("DELETE").Path("/msginfo/").Handler(
		http.NewServer(
			endpoints.DeleteEndpoint,
			_Decode_Delete_Request,
			_Encode_Delete_Response,
			opts...))
	mux.Methods("POST").Path("/msginfo/all/").Handler(
		http.NewServer(
			endpoints.GetAllEndpoint,
			_Decode_GetAll_Request,
			_Encode_GetAll_Response,
			opts...))
	mux.Methods("PUT").Path("/msginfo/").Handler(
		http.NewServer(
			endpoints.UpdateEndpoint,
			_Decode_Update_Request,
			_Encode_Update_Response,
			opts...))
	return mux
}
