// Code generated by microgen 1.0.5. DO NOT EDIT.

package service

import service "github.com/suraj.kadam7/msg-info-service/repos/msginfo"

// Service middleware (closure).
type Middleware func(service.Repository) service.Repository
