// Code generated by microgen 1.0.5. DO NOT EDIT.

package service

import service "github.com/SurajKadam7/msg-info-service/msginfo_srv"

// Service middleware (closure).
type Middleware func(service.Service) service.Service
